var Blocks = [
    {
        name: "Grass",
        width: 50,
        height: 50,
        deep: 50,
        texture: "../img/grass.png",
        icon: "../img/icons/grassIcon.png",
        contureColor: 0xffffff,
        movable: false,
        activable: false,
    },
    {
        name: "Cobblestone",
        width: 50,
        height: 50,
        deep: 50,
        texture: "../img/cobble.png",
        icon: "../img/icons/cobbleIcon.png",
        contureColor: 0xffffff,
        movable: false,
        activable: false,
    },
    {
        name: "MovingBox",
        width: 30,
        height: 30,
        deep: 30,
        texture: "../img/moving.png",
        icon: "../img/icons/movingIcon.png",
        contureColor: 0xffffff,
        movable: true,
        activable: false,
    },
]